#!/usr/bin/env python
"""Render the completed E70 secondary temporal-block analysis as auditable LaTeX macros.

Sibling of scripts/render_e70_paper_values.py (frozen).  This renderer binds the *secondary*
temporal-block artifact, whose protocol string, resampling unit, and macro namespace differ from
the preregistered primary analysis; it is kept separate from the command-destruction renderer
because its input is a single self-describing analysis JSON with its own hash-bound `inputs` list,
whereas the destruction renderer hashes twelve raw rollout reports itself.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import pathlib
from typing import Any


PROTOCOL = "E70 secondary temporal-block analysis v1"
REGISTERED_SEEDS = [0, 1, 2]
TEMPORAL_BLOCKS = 12
AMBIGUITY_PAIRS = 69
CONTRASTS = (("AT", "snmr_minus_time"), ("AS", "snmr_minus_shuffled"))


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _number(value: Any, *, signed: bool = False) -> str:
    value = float(value)
    if not math.isfinite(value) or not -1.0 <= value <= 1.0:
        raise ValueError(f"E70 temporal-block value is outside its physical range: {value}")
    return f"{value:+.3f}" if signed else f"{value:.3f}"


def _resolve_hashed_inputs(
    analysis: dict[str, Any], *, analysis_path: pathlib.Path
) -> list[pathlib.Path]:
    records = analysis.get("inputs")
    if not isinstance(records, list) or not records:
        raise ValueError("temporal-block analysis has no hash-bound inputs")
    resolved: list[pathlib.Path] = []
    for record in records:
        try:
            raw_path = pathlib.Path(record["path"])
            wanted = str(record["sha256"])
        except (KeyError, TypeError) as exc:
            raise ValueError("temporal-block analysis has a malformed input record") from exc
        path = raw_path if raw_path.is_absolute() else analysis_path.parent / raw_path
        path = path.resolve()
        if not path.is_file() or sha256_file(path) != wanted:
            raise ValueError(f"analysis input hash mismatch: {path}")
        resolved.append(path)
    return resolved


def _validate_block_definition(analysis: dict[str, Any]) -> None:
    definition = analysis.get("block_definition")
    if not isinstance(definition, dict):
        raise ValueError("temporal-block analysis lacks its block definition")
    try:
        declared = int(definition["temporal_blocks"])
        blocks = definition["blocks"]
        pair_counts = [int(count) for count in definition["pair_counts"]]
    except (KeyError, TypeError, ValueError) as exc:
        raise ValueError("temporal-block analysis has a malformed block definition") from exc
    if declared != TEMPORAL_BLOCKS or len(blocks) != TEMPORAL_BLOCKS:
        raise ValueError("temporal-block analysis does not carry the completed 12 blocks")
    if len(pair_counts) != TEMPORAL_BLOCKS or sum(pair_counts) != AMBIGUITY_PAIRS:
        raise ValueError("temporal blocks do not partition the 69 ambiguity pairs")


def latex_macros(
    analysis: dict[str, Any],
    *,
    analysis_path: pathlib.Path | None = None,
    analysis_sha256: str,
) -> str:
    if analysis.get("protocol") != PROTOCOL:
        raise ValueError("temporal-block values require the frozen E70 secondary protocol")
    if analysis.get("preview") is not False:
        raise ValueError("temporal-block values require the final, non-preview analysis")
    if analysis.get("seeds") != REGISTERED_SEEDS:
        raise ValueError("temporal-block values require completed training seeds 0, 1, and 2")
    if analysis.get("directionally_consistent") is not True:
        raise ValueError("temporal-block values require a directionally consistent analysis")
    _validate_block_definition(analysis)
    if analysis_path is not None:
        _resolve_hashed_inputs(analysis, analysis_path=analysis_path)

    lines = [
        "% Generated by scripts/render_e70_temporal_block_values.py; do not edit by hand.",
        f"% analysis_sha256={analysis_sha256}",
        rf"\newcommand{{\ETemporalBlocks}}{{{TEMPORAL_BLOCKS}}}",
    ]
    comparisons = analysis.get("comparisons", {})
    for latex_name, key in CONTRASTS:
        try:
            contrast = comparisons[key]
            difference = _number(contrast["difference"], signed=True)
            low = _number(contrast["ci95_low"])
            high = _number(contrast["ci95_high"])
            blocks = int(contrast["temporal_blocks"])
            pairs = int(contrast["pairs"])
            seeds = int(contrast["training_seeds"])
        except (KeyError, TypeError, ValueError) as exc:
            raise ValueError(f"analysis is missing the {latex_name} temporal contrast") from exc
        if (
            blocks != TEMPORAL_BLOCKS
            or pairs != AMBIGUITY_PAIRS
            or seeds != len(REGISTERED_SEEDS)
            or not float(low) <= float(difference) <= float(high)
        ):
            raise ValueError(f"analysis has an invalid {latex_name} temporal contrast")
        if contrast.get("positive_direction") is not True or contrast.get(
            "ci_excludes_zero_positive"
        ) is not True:
            raise ValueError(f"the {latex_name} temporal contrast is not directionally resolved")
        lines.extend(
            [
                rf"\newcommand{{\ETemporal{latex_name}Difference}}{{{difference}}}",
                rf"\newcommand{{\ETemporal{latex_name}CILow}}{{{low}}}",
                rf"\newcommand{{\ETemporal{latex_name}CIHigh}}{{{high}}}",
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--analysis", type=pathlib.Path, required=True)
    parser.add_argument("--out", type=pathlib.Path, required=True)
    args = parser.parse_args()
    analysis = json.loads(args.analysis.read_text())
    rendered = latex_macros(
        analysis,
        analysis_path=args.analysis,
        analysis_sha256=sha256_file(args.analysis),
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.out.with_suffix(args.out.suffix + ".tmp")
    temporary.write_text(rendered)
    temporary.replace(args.out)
    print(f"rendered frozen E70 temporal-block values -> {args.out}")


if __name__ == "__main__":
    main()
