#!/usr/bin/env python
"""Render frozen three-seed E70 quantities as auditable LaTeX macros."""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
from typing import Any


ARM_NAMES = {
    "explicit": "Explicit",
    "snmr": "Snmr",
    "time": "Time",
    "proprio": "Proprio",
    "shuffled": "Shuffled",
}
SEED_NAMES = {0: "Zero", 1: "One", 2: "Two"}


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _number(value: Any, *, signed: bool = False) -> str:
    value = float(value)
    if not -1.0 <= value <= 10.01:
        raise ValueError(f"E70 value is outside its physical range: {value}")
    return f"{value:+.3f}" if signed else f"{value:.3f}"


def _completion(value: Any) -> str:
    value = float(value)
    if not 0.0 <= value <= 1.0:
        raise ValueError(f"E70 completion is outside [0, 1]: {value}")
    return f"{value:.3f}"


def _survival(value: Any) -> str:
    value = float(value)
    if not 0.0 <= value <= 10.01:
        raise ValueError(f"E70 survival is outside [0, 10.01]: {value}")
    return f"{value:.3f}"


def latex_macros(analysis: dict[str, Any], *, analysis_sha256: str) -> str:
    if analysis.get("protocol") != "E70 preregistered analysis v1":
        raise ValueError("paper values require the frozen E70 protocol")
    if analysis.get("seeds") != [0, 1, 2]:
        raise ValueError("paper values require completed training seeds 0, 1, and 2")
    lines = [
        "% Generated by scripts/render_e70_paper_values.py; do not edit by hand.",
        f"% analysis_sha256={analysis_sha256}",
        r"\newcommand{\ETrainingSeeds}{0, 1, 2}",
    ]
    arms = analysis.get("arms", {})
    for arm, latex_name in ARM_NAMES.items():
        try:
            values = arms[arm]
            general = _completion(values["general_completion"])
            ambiguity = _completion(values["ambiguity_completion"])
            survival = _survival(values["ambiguity_survival_s"])
        except (KeyError, TypeError) as exc:
            raise ValueError(f"analysis is missing the {arm} endpoint") from exc
        lines.extend(
            [
                rf"\newcommand{{\E{latex_name}General}}{{{general}}}",
                rf"\newcommand{{\E{latex_name}Amb}}{{{ambiguity}}}",
                rf"\newcommand{{\E{latex_name}Survival}}{{{survival}}}",
            ]
        )

    for latex_name, key in (("AT", "snmr_minus_time"), ("AS", "snmr_minus_shuffled")):
        try:
            contrast = analysis[key]
            difference = _number(contrast["difference"], signed=True)
            low = _number(contrast["ci95_low"])
            high = _number(contrast["ci95_high"])
            clusters = int(contrast["clusters"])
        except (KeyError, TypeError) as exc:
            raise ValueError(f"analysis is missing the {latex_name} contrast") from exc
        if clusters != 69 or not float(low) <= float(difference) <= float(high):
            raise ValueError(f"analysis has an invalid {latex_name} contrast")
        lines.extend(
            [
                rf"\newcommand{{\E{latex_name}Difference}}{{{difference}}}",
                rf"\newcommand{{\E{latex_name}CILow}}{{{low}}}",
                rf"\newcommand{{\E{latex_name}CIHigh}}{{{high}}}",
            ]
        )

    per_seed = analysis.get("per_seed_differences", {})
    for seed, seed_name in SEED_NAMES.items():
        try:
            values = per_seed[str(seed)]
            at = _number(values["snmr_minus_time"], signed=True)
            ass = _number(values["snmr_minus_shuffled"], signed=True)
        except (KeyError, TypeError) as exc:
            raise ValueError(f"analysis is missing seed {seed} contrasts") from exc
        lines.extend(
            [
                rf"\newcommand{{\EATSeed{seed_name}}}{{{at}}}",
                rf"\newcommand{{\EASSeed{seed_name}}}{{{ass}}}",
            ]
        )

    per_clip = analysis.get("snmr_minus_time_per_clip", {})
    for side, latex_name in (("first", "First"), ("second", "Second")):
        try:
            values = per_clip[side]
            difference = _number(values["difference"], signed=True)
            low = _number(values["ci95_low"])
            high = _number(values["ci95_high"])
            clusters = int(values["clusters"])
        except (KeyError, TypeError) as exc:
            raise ValueError(f"analysis is missing the {side} clip contrast") from exc
        if clusters != 69 or not float(low) <= float(difference) <= float(high):
            raise ValueError(f"analysis has an invalid {side} clip contrast")
        lines.extend(
            [
                rf"\newcommand{{\EAT{latex_name}}}{{{difference}}}",
                rf"\newcommand{{\EAT{latex_name}Low}}{{{low}}}",
                rf"\newcommand{{\EAT{latex_name}High}}{{{high}}}",
            ]
        )

    explicit_gate = analysis.get("explicit_general_gate")
    if not isinstance(explicit_gate, bool):
        raise ValueError("analysis is missing the frozen explicit capability gate")
    positive_gate = analysis.get("positive_content_gate")
    if not isinstance(positive_gate, bool):
        raise ValueError("analysis is missing the frozen positive-content gate")
    if positive_gate and not explicit_gate:
        raise ValueError("positive-content gate cannot pass when explicit capability fails")
    lines.extend(
        [
            rf"\newcommand{{\EExplicitGate}}{{{'PASS' if explicit_gate else 'FAIL'}}}",
            rf"\newcommand{{\EPositiveGate}}{{{'PASS' if positive_gate else 'FAIL'}}}",
            rf"\eexplicitvalid{'true' if explicit_gate else 'false'}",
            rf"\epositivecontent{'true' if positive_gate else 'false'}",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--analysis", type=pathlib.Path, required=True)
    parser.add_argument("--out", type=pathlib.Path, required=True)
    args = parser.parse_args()
    analysis = json.loads(args.analysis.read_text())
    rendered = latex_macros(analysis, analysis_sha256=sha256_file(args.analysis))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    temporary = args.out.with_suffix(args.out.suffix + ".tmp")
    temporary.write_text(rendered)
    temporary.replace(args.out)
    print(f"rendered frozen E70 paper values -> {args.out}")


if __name__ == "__main__":
    main()
